source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'sqlite3'
gem 'ar-octopus', '0.6.0'
gem 'pry'

group :test do
  gem 'capybara', '>= 2.1.0'
  gem 'cucumber-rails', '>= 1.3.1', :require => false
  gem 'launchy'
  gem 'rspec-rails'
  gem 'aruba'
  gem 'database_cleaner'
end
